name: build
on:
  schedule:
  - cron: "0 8 * * *"
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker image build -t mpcurses:latest .

    - name: Prepare coverage
      run: |
        ID=$(docker create mpcurses)
        docker cp $ID:/code/target/reports/mpcurses_coverage.xml mpcurses_coverage.xml
        sed -i -e 's,filename="mpcurses/,filename="src/main/python/mpcurses/,g' mpcurses_coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: mpcurses_coverage.xml